export interface Achievement { id:string; name:string; group:string; metric:string; tiers:readonly number[]; description:string; glyph:string; }
const family=(id:string,name:string,group:string,metric:string,tiers:number[],description:string,glyph:string):Achievement=>({id,name,group,metric,tiers,description,glyph});
export const ACHIEVEMENTS:readonly Achievement[]=[
 family('rift-delver','Breach breaker','Rifts','riftClears',[1,10,50],'Defeat rift guardians before the timer expires.','star'),
 family('rift-keyed','Into the storm','Rifts','riftKeyedClears',[1,10,50],'Clear rifts empowered by a key.','gem'),
 family('rift-height','Beyond the veil','Rifts','highestRiftLevel',[30,60,100],'Clear a rift at this level or higher.','crown'),
 family('rift-speed','Against the void','Rifts','riftFastClears',[1,10,25],'Clear a rift, including its guardian, within five minutes.','spark'),
 family('rift-worlds','Fractured worlds','Rifts','riftBiomes',[3,6,9],'Clear rifts in different biomes.','compass'),
 family('rift-keys','Master of the breach','Rifts','highestRiftKeyTier',[3,4,5],'Clear rifts using Rare, Epic, then Legendary keys.','gem'),
 family('slayer','Slayer','Combat','kills',[100,1000,10000],'Defeat enemies.','blade'),
 family('veterans','Battle tested','Combat','rank:veteran',[10,100,1000],'Defeat veterans.','blade'),
 family('elites','Elite hunter','Combat','rank:elite',[5,50,500],'Defeat elites.','crown'),
 family('bosses','Kingslayer','Combat','bosses',[1,10,50],'Defeat dungeon and wilderness bosses.','crown'),
 family('matriarch','Briar breaker','Combat','boss:briarMatriarch',[1,5,20],'Defeat Briar Matriarchs.','crown'),
 family('colossus','Cold furnace','Combat','boss:ashColossus',[1,5,20],'Defeat Ashbound Colossi.','flame'),
 family('marshal','Last command','Combat','boss:graveMarshal',[1,5,20],'Defeat Grave Marshals.','blade'),
 family('damage','Force of nature','Combat','damage',[10000,100000,1000000],'Deal damage, excluding overkill.','spark'),
 family('critical','Perfect strike','Combat','crits',[50,500,5000],'Land critical hits.','spark'),
 family('largest','Heavy hitter','Combat','largestHit',[100,1000,10000],'Deal damage in a single hit.','blade'),
 family('fire','Ashmaker','Combat','damage:fire',[1000,10000,100000],'Deal fire damage.','flame'),
 family('frost','Winterborn','Combat','damage:frost',[1000,10000,100000],'Deal frost damage.','star'),
 family('lightning','Stormcaller','Combat','damage:lightning',[1000,10000,100000],'Deal lightning damage.','spark'),
 family('dot','Slow burn','Combat','periodicDamage',[1000,10000,100000],'Deal damage over time.','flame'),
 family('hybrid','Spellblade','Combat','feat:spellblade',[1],'Defeat an enemy after hitting it with melee and a spell.','star'),
 family('lastbreath','Last breath','Survival','feat:lastbreath',[1],'Defeat an elite below 10% life.','heart'),
 family('blocks','Hold the line','Survival','blocks',[25,250,2500],'Block incoming attacks.','shield'),
 family('prevented','Unbroken','Survival','damageBlocked',[1000,10000,100000],'Prevent damage by blocking.','shield'),
 family('healed','Second wind','Survival','healing',[1000,10000,100000],'Restore missing life.','heart'),
 family('potions','Deep draught','Survival','potions',[10,100,1000],'Use the dual potion.','flask'),
 family('distance','Wayfarer','Exploration','distance',[10000,100000,1000000],'Travel on foot. Teleports do not count.','compass'),
 family('biomes','Worldwalker','Exploration','biomes',[3,6,9],'Visit different biomes.','compass'),
 family('places','Trailblazer','Exploration','places',[10,50,250],'Discover places.','compass'),
 family('events','Answer the call','Exploration','events',[5,25,100],'Complete wilderness events.','star'),
 family('crypts','Crypt delver','Exploration','crypts',[1,10,50],'Clear dungeon bosses and finish crypts.','crown'),
 family('waves','Against the clock','Exploration','bestWaves',[3,6,10],'Complete waves in one cursed-chest trial.','flame'),
 family('journeys','A path of your own','Exploration','journeys',[5,25,100],'Complete Journey objectives.','compass'),
 family('wealth','Fortune seeker','Loot','goldEarned',[1000,10000,100000],'Earn gold from pickups and sales.','coin'),
 family('collector','Collector','Loot','items',[25,250,2500],'Collect equipment from the ground.','gem'),
 family('rare','Golden promise','Loot','items:rare',[1,25,100],'Collect Rare equipment.','gem'),
 family('legendary','Legend found','Loot','items:legendary',[1,5,25],'Collect Legendary equipment.','crown'),
 family('masterwork','Masterwork','Loot','highestEnhancement',[10],'Enhance an item to +10.','hammer'),
 family('level','Ever growing','Progression','highestLevel',[10,25,50,100],'Reach a character level.','star'),
 family('caster','Practiced hand','Progression','casts',[100,1000,10000],'Use assigned skills.','spark'),
 family('mana','Deep reserves','Progression','manaSpent',[1000,10000,100000],'Spend mana on attacks and skills.','flask'),
];
export function achievementValue(a:Achievement,values:Record<string,number>):number {
 return a.metric==='riftBiomes'?Object.keys(values).filter(k=>k.startsWith('seen:riftBiome:')&&values[k]>0).length:a.metric==='biomes'?Object.keys(values).filter(k=>k.startsWith('seen:biome:')&&values[k]>0).length:values[a.metric]??0;
}
export function achievementTier(a:Achievement,values:Record<string,number>):number {const n=achievementValue(a,values);return a.tiers.filter(t=>n>=t).length;}
export const STAT_GROUPS:Record<string,readonly [string,string][]>={
 Rifts:[['riftAttempts','Rifts entered'],['riftClears','Guardians defeated'],['highestRiftLevel','Highest rift cleared'],['bestRiftSeconds','Fastest clear'],['riftKeyedClears','Keyed rifts cleared'],['riftKeysUsed','Keys used'],['riftFastClears','Clears under five minutes'],['riftKills','Rift monsters slain'],['riftDeaths','Runs lost to death'],['riftTimeouts','Runs timed out'],['riftAbandoned','Runs abandoned']],
 Combat:[['kills','Enemies slain'],['damage','Damage dealt'],['directDamage','Direct damage'],['periodicDamage','Damage over time'],['hits','Hits landed'],['crits','Critical hits'],['largestHit','Largest hit'],['highestEnemy','Highest enemy level'],['bosses','Bosses defeated']],
 Survival:[['damageTaken','Damage taken'],['damageBlocked','Damage blocked'],['blocks','Blocks'],['healing','Life restored'],['manaRestored','Mana restored'],['manaSpent','Mana spent'],['potions','Potions used'],['dodges','Dodges'],['deaths','Deaths'],['longestLife','Longest life']],
 Loot:[['items','Equipment collected'],['goldEarned','Gold earned'],['goldFound','Gold picked up'],['goldSales','Gold from sales'],['goldSpent','Gold spent'],['largestGold','Largest gold pickup'],['containers','Containers broken'],['highestEnhancement','Best enhancement']],
 Exploration:[['distance','Distance travelled'],['places','Places discovered'],['events','Events completed'],['crypts','Crypts cleared'],['bestWaves','Best cursed-chest waves'],['journeys','Journey objectives']],
 Progression:[['time','Active playtime'],['highestLevel','Highest level'],['xp','Experience earned'],['casts','Skills used'],['basics','Basic attacks']],
};

/** Explain measurement rules without filling the statistics screen with extra copy. */
export const CHRONICLE_STAT_HELP:Readonly<Record<string,string>>={
 riftAttempts:'Successfully entered rifts. Failed entry or save attempts do not count.',
 riftClears:'Rift guardians defeated before time expires. Each run counts once, independently of chest collection.',
 highestRiftLevel:'The highest rift level you have cleared, including keyed rifts.',
 bestRiftSeconds:'Fastest full clear including the guardian, across all levels and keys. Pauses and offline time are excluded.',
 riftKeyedClears:'Successful clears with an optional key consumed on entry. Tracked from this update.',
 riftKeysUsed:'Keys consumed by successful entry transactions. Tracked from this update.',
 riftFastClears:'Full clears within five active minutes, including the guardian. Tracked from this update.',
 riftKills:'Hunt monsters actually defeated. Enemies removed when the guardian arrives do not count. Tracked from this update.',
 riftDeaths:'Runs ended by player death. Tracked from this update.',
 riftTimeouts:'Runs ended when the ten-minute timer expired. Tracked from this update.',
 riftAbandoned:'Unfinished runs left voluntarily. Pausing or closing the game is not abandonment. Tracked from this update.',
 time:'Time spent playing. Paused menus and closed sessions do not count.',
 damage:'Actual enemy life removed by your attacks and effects. Overkill is excluded.',
 directDamage:'Damage from direct hits, excluding damage over time.',
 periodicDamage:'Damage from ongoing effects such as burning.',
 largestHit:'The most enemy life removed by one hit. Overkill is excluded.',
 highestEnemy:'The highest-level enemy you have defeated.',
 damageTaken:'Actual life lost to incoming damage.',
 damageBlocked:'Damage prevented by successful blocks.',
 healing:'Missing life restored. Healing beyond maximum life does not count.',
 manaRestored:'Missing mana restored. Restoration beyond maximum mana does not count.',
 manaSpent:'Mana paid for attacks, assigned skills and maintained spells.',
 longestLife:'Longest active time without dying. Pauses do not count.',
 goldEarned:'Gold collected from the ground plus proceeds from vendor sales.',
 goldSpent:'Gold spent at vendors, including purchases and item improvements.',
 largestGold:'The largest single pile of gold collected.',
 highestEnhancement:'Highest enhancement reached on a piece of equipment.',
 distance:'Distance travelled on foot. Teleports do not count.',
 events:'Completed wilderness events whose rewards have been awarded.',
 crypts:'Crypts cleared by defeating their final boss.',
 bestWaves:'Most waves cleared in one cursed-chest challenge.',
 journeys:'Completed Journey objectives, including those completed without tracking them.',
 highestLevel:'Highest character level reached in this history.',
 casts:'Successful activations of assigned skills. Basic weapon attacks are counted separately.',
 basics:'Basic weapon attacks started. Each attack counts once, even when it hits multiple enemies.',
};
