/** Primary promises and tradeoffs; resolved numbers belong to the adjacent comparison. */
export const TECHNIQUE_SUMMARIES: Readonly<Record<string, string>> = {
  'repulse-wide':'A wider, full-circle shockwave; less damage.',
  'repulse-pin':'Longer stun in a narrower arc.',
  'repulse-ready':'Cheaper, faster recovery; less damage and a shorter stun.',
  'citadel-long':'Longer protection; weaker reduction and impact.',
  'citadel-seal':'Stronger protection for a shorter window.',
  'citadel-break':'Harder impact with a stun; weaker protection.',
  'smoke-wide':'Wider smoke; weaker protection.',
  'smoke-deep':'Stronger slow in a smaller area.',
  'smoke-ready':'Cheaper, faster recovery; shorter protection and slow.',
  'reaping-many':'Reach more enemies; less damage per strike.',
  'reaping-single':'Focus doubled damage on one enemy; rear strikes remain stronger.',
  'reaping-rear':'Stronger rear strikes; weaker base hits.',
  'sidestep-long':'Travel farther; slower recovery.',
  'sidestep-short':'Shorter step; faster recovery.',
  'sidestep-retreat':'Step backward while aiming forward; cheaper, shorter travel.',
  'brace-long':'Longer Brace; weaker reduction.',
  'brace-hard':'Stronger Brace for a shorter window.',
  'brace-ready':'Cheaper, faster recovery; weaker reduction.',
  'ward-deep':'Larger Ward; shorter duration.',
  'ward-lasting':'Longer Ward; less absorption.',
  'ward-renew':'Cheaper, faster recovery; smaller, shorter Ward.',
  'vault-long':'Retreat farther; weaker arrow.',
  'vault-close':'Shorter retreat; stronger arrow.',
  'vault-advance':'Vault forward; weaker arrow and faster recovery.',
  'rally-last':'Longer, stronger protection; only one empowered action.',
  'rally-march':'More empowered actions; weaker protection.',
  'rally-burst':'One stronger melee action; shorter window and no protection.',
  'ghost-patient':'Fewer, stronger echoes in a longer window.',
  'ghost-flurry':'More, weaker echoes in a shorter window.',
  'ghost-focus':'One powerful echo in a shorter window.',
  'cleave-economy':'Cheaper, narrower sweep; less damage.',
  'cleave-reach':'Longer sweep; less damage.',
  'cleave-force':'Stronger sweep; less reach.',
  'whirlwind-economy':'Cheaper spin; less damage.',
  'whirlwind-reach':'Wider spin; less damage.',
  'whirlwind-force':'Stronger spin; less reach.',
  'ricochet-pierce':'Pierce before rebounding; fewer rebounds and less damage.',
  'ricochet-chain':'More rebounds; less damage.',
  'ricochet-force':'One stronger rebound.',
  'backstab-economy':'Cheaper strike with an easier rear angle; less damage.',
  'backstab-reach':'Longer reach; less damage.',
  'backstab-rear':'Stronger rear multiplier; weaker base hits.',
  'shield-wide':'Wider, longer strike; less damage.',
  'shield-force':'Stronger strike and longer stun.',
  'shield-control':'Longer stun; less damage.',
  'volley-fan':'More arrows; less damage per arrow.',
  'volley-pierce':'Each arrow pierces another enemy.',
  'volley-focus':'Tighter fan; stronger arrows.',
  'fireball-fork':'Three Fireballs; less damage per projectile.',
  'fireball-ember':'Explosions leave burning ground.',
  'fireball-impact':'Wider explosion; less damage.',
  'arc-circuit':'More jumps can revisit targets at reduced damage.',
  'arc-focus':'Stronger lightning; fewer targets.',
  'arc-economy':'Cheaper, weaker lightning; later jumps retain more damage.',
  'nova-echo':'A second, weaker nova repeats at the same position.',
  'nova-deep':'Wider nova with a stronger, longer slow; less damage.',
  'nova-freeze':'Freezes enemies; smaller nova and less damage.',
  'meteor-shards':'More scattered impacts; smaller and weaker explosions.',
  'meteor-inferno':'Longer ground fire.',
  'meteor-impact':'Larger, stronger impact; no ground fire.',
  'lunge-distance':'Longer dash; less damage.',
  'lunge-force':'Wider contact; more damage.',
  'lunge-swift':'Cheaper, faster recovery; shorter dash and less damage.',
  'earthshatter-wide':'Wider shockwave; less damage.',
  'earthshatter-force':'Stronger impact and longer stun; smaller area.',
  'earthshatter-swift':'Faster recovery; less damage and a shorter stun.',
  'bulwark-duration':'Guard for longer.',
  'bulwark-reduction':'Stronger block for a shorter window.',
  'bulwark-swift':'Cheaper, faster recovery; shorter guard.',
  'piercing-depth':'Pierce more enemies; less damage.',
  'piercing-force':'Stronger arrow; fewer targets.',
  'piercing-twin':'Two piercing arrows; less damage per arrow.',
  'rain-wide':'Wider rain; less damage per wave.',
  'rain-lasting':'More waves; less damage per wave.',
  'rain-burst':'Fewer, faster, stronger waves.',
  'lance-fan':'Three lances; less damage per lance.',
  'lance-chill':'Stronger, longer slow; less damage.',
  'lance-force':'Stronger lance; fewer targets.',
  'siphon-drain':'More healing from actual damage; weaker hit.',
  'siphon-pierce':'Pierce more enemies; less damage.',
  'siphon-force':'Stronger hit; less healing.',
  'cataclysm-many':'More impacts; less damage per impact.',
  'cataclysm-force':'Fewer, larger, stronger impacts.',
  'cataclysm-fire':'Longer ground fire; weaker impacts.',
  'tempest-wide':'Wider storm; weaker strikes.',
  'tempest-fast':'Faster, weaker strikes.',
  'tempest-still':'Longer, stronger storm; stays where cast.',
  'zero-wide':'Wider waves; less damage.',
  'zero-freeze':'Longer freeze and stronger, longer slow.',
  'zero-burst':'One stronger wave; smaller area.',
};
