import test from 'node:test';
import assert from 'node:assert/strict';
import { IDBFactory } from 'fake-indexeddb';
import { emptyChronicle, freshChronicle, metric, chronicleValues, recordChronicle, mergeChronicles, forkChronicle, validChronicle, parseChronicleLedger, progressForRecord, type ChronicleLedger } from '../src/chronicle.ts';
import { ACHIEVEMENTS, achievementTier } from '../src/chronicle-content.ts';
import { trackChronicleEvent, trackCommerce } from '../src/chronicle-tracking.ts';
import { Simulation } from '../src/simulation.ts';
import { damageEnemy, damagePlayer } from '../src/combat-damage.ts';
import { CharacterSession } from '../src/character-session.ts';
import { CharacterRepository, type SaveResult } from '../src/character-storage.ts';
import { CHARACTER_SAVE_VERSION, type CharacterSave } from '../src/character-save.ts';
import { openSaveDatabase } from '../src/save-database.ts';
import { makeSaveBundle } from '../src/save-bundle.ts';
import { openCloudCache, type CloudRow } from '../src/cloud-cache.ts';
import { WORLD_GENERATION_VERSION } from '../src/world.ts';
import type { CombatEvent, Input } from '../src/model.ts';
const world={seed:7319,isSanctuary:()=>false,blocked:()=>false,move:(x:number,y:number,dx:number,dy:number)=>({x:x+dx,y:y+dy})};
const counts=(c:ChronicleLedger)=>chronicleValues(Object.values(c.sources));
function record(id='rowan',kills=0):CharacterSave {const sim=new Simulation(world,{spawn:false}),c=sim.captureCheckpoint();c.chronicle=freshChronicle(id,id,1);metric(c.chronicle,'kills',kills);return {version:CHARACTER_SAVE_VERSION,id,name:id,createdAt:1,updatedAt:100,worldSeed:7319,worldVersion:WORLD_GENERATION_VERSION,checkpoint:c};}
const input:Input={moveX:0,moveY:0,aimX:100,aimY:0,attack:false,dodge:false,heal:false,skillSlot:null};
test('cumulative checkpoints, retries and out-of-order reads do not double-count',()=>{const a=record('a',80),old=record('a',20),b=record('b',70);let ledger=recordChronicle(emptyChronicle(),a);ledger=recordChronicle(ledger,b);ledger=recordChronicle(ledger,a);ledger=recordChronicle(ledger,old);assert.equal(counts(ledger).kills,150);assert.equal(ledger.unlocked['slayer:1'],100);assert.deepEqual(mergeChronicles(ledger,ledger),ledger);});
test('import shares old history and counts new play separately, including re-imports',()=>{const a=record('a',80),b=record('b');b.checkpoint.chronicle=forkChronicle(a,'b');metric(b.checkpoint.chronicle,'kills',10);const c=record('c');c.checkpoint.chronicle=forkChronicle(b,'c');metric(c.checkpoint.chronicle,'kills',5);let ledger=emptyChronicle();for(const r of[a,b,c,a,c])ledger=recordChronicle(ledger,r);assert.equal(counts(ledger).kills,95);assert.equal(chronicleValues(b.checkpoint.chronicle.sources).kills,90);assert.equal(chronicleValues(c.checkpoint.chronicle.sources).kills,95);});
test('records use maxima, totals use sums, unlock dates stay at the first checkpoint',()=>{const a=record('a',100),b=record('b',200);metric(a.checkpoint.chronicle,'largestHit',600);metric(b.checkpoint.chronicle,'largestHit',400);const first=recordChronicle(emptyChronicle(),a);a.updatedAt=500;const latest=recordChronicle(recordChronicle(first,b),a);assert.equal(counts(latest).largestHit,600);assert.equal(latest.unlocked['slayer:1'],100);assert.equal(counts(latest).kills,300);});
test('old saves backfill only recorded kills, time and level and mark unknown history',()=>{const r=record();delete r.checkpoint.chronicle;r.checkpoint.kills=42;r.checkpoint.time=120;const p=progressForRecord(r),v=chronicleValues(p.sources);assert.equal(v.kills,42);assert.equal(v.time,120);assert.equal(v.highestLevel,1);assert.equal(v['seen:legacy'],1);assert.equal(v.damage,undefined);assert.equal(r.checkpoint.chronicle,undefined);});
test('malformed metrics, duplicate sources and prototype keys are rejected',()=>{const p=freshChronicle('a');for(const n of[-1,NaN,Infinity]){p.sources[0].values.kills=n;assert.equal(validChronicle(p),false);}p.sources[0].values={};p.sources.push({...p.sources[0]});assert.equal(validChronicle(p),false);assert.throws(()=>parseChronicleLedger('{"version":1,"sources":{"__proto__":{"id":"__proto__"}},"characters":{},"unlocked":{}}'));assert.throws(()=>parseChronicleLedger('{"version":1,"sources":{},"characters":{"a":null},"unlocked":{}}'));});
test('session saves preserve original achievement date without requiring a reload',async()=>{const data=new Map<string,string>(),repo=new CharacterRepository({getItem:k=>data.get(k)??null,setItem:(k,v)=>{data.set(k,v);}}),session=new CharacterSession(repo,WORLD_GENERATION_VERSION),r=record('a',100);assert.ok(await session.create(0,'a',7319,r.checkpoint,'a',100));const checkpoint=structuredClone(r.checkpoint);checkpoint.chronicle!.sources[0].unlocked={};assert.ok(await session.save(checkpoint,200));assert.equal(session.active!.record.checkpoint.chronicle!.sources[0].unlocked['slayer:1'],100);});
test('local deletion retains history, stale writes cannot change it, import remains deduplicated',async()=>{const db=openSaveDatabase(new IDBFactory());try{const r=record('a',100);const saved=await db.execute({id:1,method:'write',index:0,record:r,expected:null}) as SaveResult;assert.ok(saved.ok);assert.ok((await db.execute({id:2,method:'remove',index:0,expected:saved.token}) as SaveResult).ok);let history=await db.execute({id:3,method:'chronicle'}) as ChronicleLedger;assert.equal(counts(history).kills,100);assert.equal(history.characters.a.deleted,true);r.checkpoint.chronicle!.sources[0].values.kills=900;assert.equal((await db.execute({id:4,method:'write',index:0,record:r,expected:saved.token}) as SaveResult).ok,false);history=await db.execute({id:5,method:'chronicle'}) as ChronicleLedger;assert.equal(counts(history).kills,100);r.checkpoint.chronicle!.sources[0].values.kills=100;assert.ok((await db.execute({id:6,method:'import',index:1,raw:JSON.stringify(makeSaveBundle(r)),expected:null}) as SaveResult).ok);assert.equal(counts(await db.execute({id:7,method:'chronicle'}) as ChronicleLedger).kills,100);}finally{await db.close();}});
test('cloud history cache survives restart, remains account-owned and excludes unacknowledged conflict history',async()=>{const factory=new IDBFactory(),a=openCloudCache(factory,'A'),b=openCloudCache(factory,'B');try{const ledger=recordChronicle(emptyChronicle(),record('remote',150));await a.execute({kind:'history',ledger});assert.equal(counts(await a.execute({kind:'read-history'}) as ChronicleLedger).kills,150);assert.deepEqual(await b.execute({kind:'read-history'}),emptyChronicle());const row=await a.execute({kind:'write',index:0,expected:null,bundle:makeSaveBundle(record('pending',900)),operation:'pending'}) as CloudRow;assert.deepEqual(row.history,emptyChronicle());await a.execute({kind:'conflict',index:0,base:0});assert.deepEqual((await a.execute({kind:'read',index:0}) as CloudRow).history,emptyChronicle());}finally{await a.close();await b.close();}const reopened=openCloudCache(factory,'A');try{assert.equal(counts(await reopened.execute({kind:'read-history'}) as ChronicleLedger).kills,150);}finally{await reopened.close();}});
test('overkill is excluded and hybrid physical/element damage partitions the real hit',()=>{const sim=new Simulation(world,{spawn:false}),p=sim.player,e=sim.spawnEnemy('brute',100,0)!,events:CombatEvent[]=[];e.hp=50;const context={player:p,enemies:sim.enemies,random:()=>1,visible:()=>true,killed:()=>{},emit:(event:CombatEvent)=>{events.push(event);trackChronicleEvent(p,sim.enemies,event);}};damageEnemy(e,100,0,true,context,false,'fire',20);const v=chronicleValues(p.chronicle!.sources);assert.equal(v.damage,50);assert.equal(v['damage:fire'],10);assert.equal(v['damage:physical'],40);assert.equal(v.kills,1);damageEnemy(e,100,0,true,context);assert.equal(v.kills,1);assert.equal(events.filter(e=>e.type==='kill').length,1);});
test('Spellblade needs both melee and magic on the same enemy; crit and periodic totals stay separate',()=>{const sim=new Simulation(world,{spawn:false}),p=sim.player,e=sim.spawnEnemy('brute',100,0)!;e.hp=500;const context={player:p,enemies:sim.enemies,random:()=>1,visible:()=>true,killed:()=>{},emit:(event:CombatEvent)=>trackChronicleEvent(p,sim.enemies,event)};damageEnemy(e,25,0,true,context,false,'fire',5);assert.equal(chronicleValues(p.chronicle!.sources)['feat:spellblade'],undefined);damageEnemy(e,25,0,false,context,true,'fire');damageEnemy(e,900,0,false,context,false,'fire',undefined,{critChance:0,critMultiplier:1,lifeOnHit:0,skill:'fireball'});const v=chronicleValues(p.chronicle!.sources);assert.equal(v['feat:spellblade'],1);assert.equal(v.periodicDamage,25);assert.equal(v['skillDamage:fireball'],450);assert.equal(v.crits,undefined);assert.equal(v.damage,500);});
test('lethal damage records actual life removed and one death; immunity cannot add damage',()=>{const sim=new Simulation(world,{spawn:false}),p=sim.player;p.hp=9;p.equipment.offHand=null;const context={player:p,world,random:()=>1,emit:(e:CombatEvent)=>trackChronicleEvent(p,[],e)};damagePlayer(999,0,1,'physical',context);damagePlayer(999,0,1,'physical',context);const v=chronicleValues(p.chronicle!.sources);assert.equal(v.damageTaken,9);assert.equal(v.deaths,1);});
test('only simulation time and movement count; changing location does not award distance',()=>{const sim=new Simulation(world,{spawn:false});sim.player.x=0;sim.player.y=0;for(let i=0;i<120;i++)sim.update(1/120,{...input,moveX:1});let v=chronicleValues(sim.player.chronicle!.sources);assert.ok(Math.abs(v.time-1)<1e-10);assert.ok(v.distance>0&&v.distance<200);const distance=v.distance;sim.player.x+=100000;sim.update(1/120,input);v=chronicleValues(sim.player.chronicle!.sources);assert.ok(v.distance-distance<2);const snapshot=sim.captureCheckpoint();sim.restoreCheckpoint(snapshot);assert.deepEqual(sim.player.chronicle,snapshot.chronicle);});
test('commerce records only actual gold differences and enhancement records',()=>{const c=freshChronicle();trackCommerce(c,500,200,7);trackCommerce(c,200,240,5);trackCommerce(c,240,240);const v=chronicleValues(c.sources);assert.equal(v.goldSpent,300);assert.equal(v.goldEarned,40);assert.equal(v.goldSales,40);assert.equal(v.highestEnhancement,7);});
test('all achievement families have stable unique IDs, ascending tiers and reachable metrics',()=>{assert.equal(ACHIEVEMENTS.length,35);assert.equal(new Set(ACHIEVEMENTS.map(a=>a.id)).size,35);for(const a of ACHIEVEMENTS){assert.ok(a.tiers.every((n,i)=>n>0&&(!i||n>a.tiers[i-1])));assert.equal(achievementTier(a,{}),0);}});

test('early local Chronicle history is upgraded without blocking saves or losing counters',async()=>{const factory=new IDBFactory(),db=openSaveDatabase(factory);try{const r=record('a',100),saved=await db.execute({id:1,method:'write',index:0,expected:null,record:r}) as SaveResult;assert.ok(saved.ok);const early=recordChronicle(emptyChronicle(),r) as Partial<ChronicleLedger>;delete early.unlocked;
 await new Promise<void>((resolve,reject)=>{const open=factory.open('evergrow-local');open.onerror=()=>reject(open.error);open.onsuccess=()=>{const raw=open.result,tx=raw.transaction('characters','readwrite');tx.objectStore('characters').put(['chronicle',JSON.stringify(early)],'chronicle');tx.oncomplete=()=>{raw.close();resolve();};tx.onerror=()=>{raw.close();reject(tx.error);};};});
 const recovered=await db.execute({id:2,method:'chronicle'}) as ChronicleLedger;assert.equal(counts(recovered).kills,100);metric(r.checkpoint.chronicle,'kills',1);assert.ok((await db.execute({id:3,method:'write',index:0,expected:saved.token,record:r}) as SaveResult).ok);assert.equal(counts(await db.execute({id:4,method:'chronicle'}) as ChronicleLedger).kills,101);
 }finally{await db.close();}});

test('compact cloud history shows pending progress but excludes conflicted recovery and preserves acknowledged history',async()=>{
 const cache=openCloudCache(new IDBFactory(),'projection');
 try{
  const accepted=record('rowan',20);
  let row=await cache.execute({kind:'adopt',index:0,expected:null,bundle:makeSaveBundle(accepted),base:1}) as CloudRow;
  row=await cache.execute({kind:'write',index:0,expected:row.token,bundle:makeSaveBundle(record('rowan',80)),operation:'pending'}) as CloudRow;
  assert.equal(counts(await cache.execute({kind:'chronicle'}) as ChronicleLedger).kills,80);
  await cache.execute({kind:'conflict',index:0,base:1});
  const view=await cache.execute({kind:'chronicle'}) as ChronicleLedger;
  assert.equal(counts(view).kills,20);
  assert.equal('bundle' in view,false);
  assert.equal(counts(await cache.execute({kind:'read-history'}) as ChronicleLedger).kills,undefined,'viewing pending progress does not permanently merge it');
 }finally{await cache.close();}
});
