import test from 'node:test';
import assert from 'node:assert/strict';
import { Simulation } from '../src/simulation.ts';
import { executeCharacterCommand } from '../src/character-commands.ts';
import { quoteService, planService, respecPoints } from '../src/commerce.ts';
import { executeService } from '../src/commerce-command.ts';
import type { TownNPC } from '../src/npcs.ts';
const world={seed:7319,blocked:()=>false,move:(x:number,y:number,dx:number,dy:number)=>({x:x+dx,y:y+dy})};
const npc:TownNPC={id:'enchanter',buildingId:'shop',name:'Vesper',role:'enchanter',x:0,y:0,seed:1,level:1};
function setup(){const sim=new Simulation(world,{spawn:false}),p=sim.player;p.level=20;p.character.skillPoints=19;p.character.statPoints=95;p.character.gold=10000;p.x=p.y=0;assert.ok(executeCharacterCommand(p,{type:'allocateNode',id:'skill:cleave'}).ok);assert.ok(executeCharacterCommand(p,{type:'upgradeSkill',skill:'cleave'}).ok);executeCharacterCommand(p,{type:'assignSkill',slot:0,skill:'cleave'});return p;}
test('respec refunds nodes and extra ranks exactly, without changing attributes or equipment',()=>{const p=setup(),before=structuredClone(p.character),count=respecPoints(before),q=quoteService(before,npc,p.level,{type:'respec'});assert.ok(q.ok);assert.equal(q.quote.price,count*25);const result=planService(before,npc,p.level,q.quote);assert.ok(result.ok);assert.equal(result.character.skillPoints,19);assert.equal(result.character.gold,10000-count*25);assert.deepEqual(result.character.allocatedNodes,['origin']);assert.deepEqual(result.character.skillSlots,Array(5).fill(null));assert.deepEqual(result.character.equipped,before.equipped);assert.deepEqual(result.character.attributes,before.attributes);assert.equal(planService(result.character,npc,p.level,q.quote).ok,false);assert.deepEqual(p.character,before);});
test('respec rechecks spent points, funds and service ownership',()=>{const p=setup(),q=quoteService(p.character,npc,p.level,{type:'respec'});assert.ok(q.ok);assert.equal(quoteService(p.character,{...npc,role:'gambler'},20,{type:'respec'}).ok,false);executeCharacterCommand(p,{type:'upgradeSkill',skill:'cleave'});assert.equal(planService(p.character,npc,20,q.quote).ok,false);p.character.gold=0;const fresh=quoteService(p.character,npc,20,{type:'respec'});assert.ok(fresh.ok);assert.equal(planService(p.character,npc,20,fresh.quote).ok,false);});
test('failed persistence leaves build, wallet, cooldowns and resources intact; success does not heal',async()=>{const p=setup();p.hp=12;p.mana=9;p.skillCooldowns={cleave:3};const before=structuredClone(p),q=quoteService(p.character,npc,20,{type:'respec'});assert.ok(q.ok);assert.equal((await executeService(p,npc,world,q.quote,()=>({ok:false}))).ok,false);assert.deepEqual(p,before);assert.equal((await executeService(p,npc,world,q.quote,()=>({ok:true}))).ok,true);assert.equal(p.hp,12);assert.equal(p.mana,9);assert.deepEqual(p.skillCooldowns,{});});
